services:
  mav-tg-crm:
    build:
      context: ..
      target: development-image
      dockerfile: ./infra/Dockerfile
    environment:
      CONFIG_FILE: "/etc/config.toml"
      MAV_ENV: "docker"
    ports:
      - "8000:80"
    configs:
      - source: backend_config
        target: /etc/config.toml
    volumes:
      - ../src/api:/app/src:ro

    develop:
      watch:
        - action: rebuild
          path: ../src
          target: /app/src

configs:
  backend_config:
    file: config.toml
