"""change_task_model

Revision ID: 16032136a812
Revises: 89c6b5ebb83a
Create Date: 2025-12-02 23:05:55.674337

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16032136a812"
down_revision: Union[str, Sequence[str], None] = "89c6b5ebb83a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=25),
        nullable=False,
        schema="mav_schema",
    )
    op.alter_column(
        "tasks",
        "priority",
        existing_type=sa.VARCHAR(length=25),
        nullable=False,
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "priority",
        existing_type=sa.VARCHAR(length=25),
        nullable=True,
        schema="mav_schema",
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=25),
        nullable=True,
        schema="mav_schema",
    )
    # ### end Alembic commands ###
