"""add_project_table

Revision ID: 28f62d1f27f3
Revises: 2ec27a088330
Create Date: 2025-10-16 19:42:57.222327

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28f62d1f27f3"
down_revision: Union[str, Sequence[str], None] = "2ec27a088330"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("owner", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["mav_schema.users.user_id"]),
        sa.ForeignKeyConstraint(["owner"], ["mav_schema.users.user_id"]),
        sa.PrimaryKeyConstraint("project_id"),
        schema="mav_schema",
    )
    op.create_table(
        "project_participants",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("added_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mav_schema.users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_participants", schema="mav_schema")
    op.drop_table("projects", schema="mav_schema")
    # ### end Alembic commands ###
