"""add_new_column_task_model

Revision ID: 2c5e42863797
Revises: 6b8f331aeac9
Create Date: 2025-11-29 14:51:33.383618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c5e42863797"
down_revision: Union[str, Sequence[str], None] = "6b8f331aeac9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("number", sa.Integer(), nullable=False),
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "number", schema="mav_schema")
    # ### end Alembic commands ###
