"""init

Revision ID: 396c2495b5a0
Revises:
Create Date: 2025-11-25 00:30:12.890243

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "396c2495b5a0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="mav_schema",
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        schema="mav_schema",
    )
    op.create_table(
        "versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("major", sa.Integer(), nullable=False),
        sa.Column("minor", sa.Integer(), nullable=False),
        sa.Column("patch", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("major", "minor", "patch"),
        schema="mav_schema",
    )
    op.create_table(
        "projects",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=25), nullable=True),
        sa.Column("owner", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner"], ["mav_schema.users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id"),
        schema="mav_schema",
    )
    op.create_table(
        "boards",
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("number_tasks", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("board_id"),
        schema="mav_schema",
    )
    op.create_table(
        "documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("link", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id"),
        schema="mav_schema",
    )
    op.create_table(
        "project_participants",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("added_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mav_schema.users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
        schema="mav_schema",
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=True),
        sa.Column("deadline", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=25), nullable=True),
        sa.Column("priority", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["board_id"], ["mav_schema.boards.board_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["mav_schema.documents.document_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mav_schema.users.user_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("task_id"),
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks", schema="mav_schema")
    op.drop_table("project_participants", schema="mav_schema")
    op.drop_table("documents", schema="mav_schema")
    op.drop_table("boards", schema="mav_schema")
    op.drop_table("projects", schema="mav_schema")
    op.drop_table("versions", schema="mav_schema")
    op.drop_table("users", schema="mav_schema")
    op.drop_table("settings", schema="mav_schema")
    # ### end Alembic commands ###
