"""create_invite_model

Revision ID: 4bd8b6e2eeea
Revises: 6924745c7102
Create Date: 2025-12-03 19:08:10.424598

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bd8b6e2eeea"
down_revision: Union[str, Sequence[str], None] = "6924745c7102"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_invites",
        sa.Column("token", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token"),
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_invites", schema="mav_schema")
    # ### end Alembic commands ###
