"""changeparti

Revision ID: 6924745c7102
Revises: 16032136a812
Create Date: 2025-12-03 13:30:40.959045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6924745c7102"
down_revision: Union[str, Sequence[str], None] = "16032136a812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_participants",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        schema="mav_schema",
    )
    op.drop_column("project_participants", "added_at", schema="mav_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_participants",
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        schema="mav_schema",
    )
    op.alter_column(
        "project_participants",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        schema="mav_schema",
    )
    # ### end Alembic commands ###
