"""task_and_columns_of_board

Revision ID: 6b8f331aeac9
Revises: 396c2495b5a0
Create Date: 2025-11-25 00:46:32.717697

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b8f331aeac9"
down_revision: Union[str, Sequence[str], None] = "396c2495b5a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_columns",
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"], ["mav_schema.boards.board_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("column_id"),
        schema="mav_schema",
    )
    op.add_column(
        "tasks",
        sa.Column("column_id", sa.UUID(), nullable=True),
        schema="mav_schema",
    )
    op.create_foreign_key(
        None,
        "tasks",
        "board_columns",
        ["column_id"],
        ["column_id"],
        source_schema="mav_schema",
        referent_schema="mav_schema",
        ondelete="SET NULL",
    )
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.BIGINT(),
        server_default=sa.text(
            "nextval('mav_schema.users_user_id_seq'::regclass)"
        ),
        existing_nullable=False,
        schema="mav_schema",
    )
    op.drop_constraint(None, "tasks", schema="mav_schema", type_="foreignkey")
    op.drop_column("tasks", "column_id", schema="mav_schema")
    op.drop_table("board_columns", schema="mav_schema")
    # ### end Alembic commands ###
