"""add_document

Revision ID: 7f8659a04da2
Revises: fdee906e4400
Create Date: 2025-11-09 21:22:57.356241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f8659a04da2"
down_revision: Union[str, Sequence[str], None] = "fdee906e4400"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("link", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["mav_schema.projects.project_id"]
        ),
        sa.PrimaryKeyConstraint("document_id"),
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents", schema="mav_schema")
    # ### end Alembic commands ###
