"""create_default_parametr

Revision ID: 89c6b5ebb83a
Revises: 2c5e42863797
Create Date: 2025-11-29 15:09:18.661120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89c6b5ebb83a"
down_revision: Union[str, Sequence[str], None] = "2c5e42863797"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "user_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "user_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        schema="mav_schema",
    )
    # ### end Alembic commands ###
