"""Add_Tasks_table

Revision ID: b97fd97586bf
Revises: dc8b3301ca48
Create Date: 2025-11-16 17:56:21.411609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97fd97586bf'
down_revision: Union[str, Sequence[str], None] = 'dc8b3301ca48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('tasks_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('responsible_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mav_schema.boards.board_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['mav_schema.documents.document_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['mav_schema.projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['mav_schema.users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tasks_id'),
    schema='mav_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks', schema='mav_schema')
    # ### end Alembic commands ###
