"""add_task_model

Revision ID: bc70ef414e37
Revises: dc8b3301ca48
Create Date: 2025-11-16 22:58:10.227300

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc70ef414e37"
down_revision: Union[str, Sequence[str], None] = "dc8b3301ca48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=True),
        sa.Column("deadline", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DONE", "NOT_DONE", name="statustask", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "FROZEN",
                name="prioritytask",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["board_id"], ["mav_schema.boards.board_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["mav_schema.documents.document_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["mav_schema.projects.project_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mav_schema.users.user_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("task_id"),
        schema="mav_schema",
    )
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "IN_PROGRESS",
            "FINISHED",
            "STOPPED",
            "PLANNED",
            name="statusproject",
            native_enum=False,
        ),
        existing_nullable=True,
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.Enum(
            "IN_PROGRESS",
            "FINISHED",
            "STOPPED",
            "PLANNED",
            name="statusproject",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        schema="mav_schema",
    )
    op.drop_table("tasks", schema="mav_schema")
    # ### end Alembic commands ###
