"""deleteowner

Revision ID: caa881abca05
Revises: 4bd8b6e2eeea
Create Date: 2025-12-03 21:05:53.391077

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caa881abca05"
down_revision: Union[str, Sequence[str], None] = "4bd8b6e2eeea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("projects_owner_fkey"),
        "projects",
        schema="mav_schema",
        type_="foreignkey",
    )
    op.drop_column("projects", "owner", schema="mav_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("owner", sa.BIGINT(), autoincrement=False, nullable=True),
        schema="mav_schema",
    )
    op.create_foreign_key(
        op.f("projects_owner_fkey"),
        "projects",
        "users",
        ["owner"],
        ["user_id"],
        source_schema="mav_schema",
        referent_schema="mav_schema",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
