"""add_board_model

Revision ID: dc8b3301ca48
Revises: 7f8659a04da2
Create Date: 2025-11-10 18:16:18.258001

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc8b3301ca48"
down_revision: Union[str, Sequence[str], None] = "7f8659a04da2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("number_tasks", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["mav_schema.projects.project_id"]
        ),
        sa.PrimaryKeyConstraint("board_id"),
        schema="mav_schema",
    )
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.BIGINT(),
        server_default=sa.text(
            "nextval('mav_schema.users_user_id_seq'::regclass)"
        ),
        existing_nullable=False,
        schema="mav_schema",
    )
    op.drop_table("boards", schema="mav_schema")
    # ### end Alembic commands ###
