"""add_short_name_for_user

Revision ID: f44a213a31e4
Revises: b9323b0d84f0
Create Date: 2025-12-04 00:06:02.610140

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f44a213a31e4"
down_revision: Union[str, Sequence[str], None] = "b9323b0d84f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("short_name", sa.String(length=100), nullable=False),
        schema="mav_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "short_name", schema="mav_schema")
    # ### end Alembic commands ###
